[workspace]
members = [
    "node",
    "pallets/template",
    "runtime",
]

[profile.release]
panic = 'unwind'
lto = true

[patch.crates-io]
pallet-timestamp = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
sp-core = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
sp-std = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
sp-io = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
frame-support = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
frame-system = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
pallet-aura = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
pallet-balances = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
pallet-grandpa = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
pallet-sudo = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
frame-try-runtime = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
frame-executive = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
frame-system-benchmarking = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
sp-api = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
sp-block-builder = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
sp-session = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
sp-version = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
sp-offchain = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
sp-inherents = { git = "https://github.com/paritytech/substrate.git", "branch" = "no-compression" }
sp-ark-bls12-381 = { git = "https://github.com/paritytech/ark-substrate", "branch" = "no-compression" }
sp-ark-bls12-377 = { git = "https://github.com/paritytech/ark-substrate", "branch" = "no-compression" }
sp-ark-bw6-761 = { git = "https://github.com/paritytech/ark-substrate", "branch" = "no-compression" }
sp-ark-ed-on-bls12-377 = { git = "https://github.com/paritytech/ark-substrate", "branch" = "no-compression" }
sp-ark-ed-on-bls12-381 = { git = "https://github.com/paritytech/ark-substrate", "branch" = "no-compression" }
sp-ark-models = { git = "https://github.com/paritytech/ark-substrate", "branch" = "no-compression" }
ark-groth16 = { git = "https://github.com/achimcc/groth16", "branch" = "master" }

