[workspace]
members = [
    "node",
    "pallets/template",
    "runtime",
]

[profile.production]
codegen-units = 1
inherits = 'release'
lto = 'fat'

[profile.release]
lto = 'thin'
panic = 'abort'

[patch.crates-io]
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "achimcc/arkworks-integration" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "achimcc/arkworks-integration" }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "achimcc/arkworks-integration" }
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "achimcc/arkworks-integration" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate.git", branch = "achimcc/arkworks-integration" }
frame-support = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "achimcc/arkworks-integration" }
frame-system = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "achimcc/arkworks-integration" }

sp-ark-bls12-381 = { git = "https://github.com/paritytech/ark-substrate" }
ark-groth16 = { git = "https://github.com/achimcc/groth16", branch = "master" }