[workspace]
members = [
    "node",
    "pallets/template",
    "runtime",
]

[profile.release]
panic = 'unwind'
lto = true

[profile.bench]
lto = true

[patch.crates-io]
sp-ark-bls12-381 = { git = "https://github.com/paritytech/ark-substrate.git", branch = "arkworks-host-function-mul" }
sp-ark-bls12-377 = { git = "https://github.com/paritytech/ark-substrate.git", branch = "arkworks-host-function-mul" }
sp-ark-ed-on-bls12-381 = { git = "https://github.com/paritytech/ark-substrate.git", branch = "arkworks-host-function-mul" }
sp-ark-ed-on-bls12-377 = { git = "https://github.com/paritytech/ark-substrate.git", branch = "arkworks-host-function-mul" }
sp-ark-bw6-761 = { git = "https://github.com/paritytech/ark-substrate.git", branch = "arkworks-host-function-mul" }
sp-ark-models = { git = "https://github.com/paritytech/ark-substrate.git", branch = "arkworks-host-function-mul" }
sp-arkworks =  { git = "https://github.com/paritytech/substrate.git", branch = "arkworks-host-function-mul" }


