[workspace]
resolver = "2"

members = [
#     "node",
    "pallets/ark-demo",
#     "runtime",
]

[profile.release]
panic = 'unwind'
lto = true

[profile.bench]
lto = true

# [patch.crates-io]
# sp-ark-bls12-381 = { git = "https://github.com/paritytech/ark-substrate.git" }
# sp-ark-bls12-377 = { git = "https://github.com/paritytech/ark-substrate.git" }
# sp-ark-ed-on-bls12-381-bandersnatch = { git = "https://github.com/paritytech/ark-substrate.git" }
# sp-ark-ed-on-bls12-377 = { git = "https://github.com/paritytech/ark-substrate.git" }
# sp-ark-bw6-761 = { git = "https://github.com/paritytech/ark-substrate.git" }
# sp-ark-models = { git = "https://github.com/paritytech/ark-substrate.git" }

[patch.crates-io]
ark-scale = { path = "/home/davxy/develop/w3f/ark-scale" }

[patch."https://github.com/w3f/ring-vrf"]
dleq_vrf = { path = "/home/davxy/develop/w3f/ring-vrf/dleq_vrf" }
bandersnatch_vrfs = { path = "/home/davxy/develop/w3f/ring-vrf/bandersnatch_vrfs" }
