name: Check Set-Up & Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:   

  bench:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown   

      - name: Install protoc
        uses: taiki-e/install-action@v1
        with:
          tool: protoc  
      
      - name: Build benchmarks
        run: |
          cargo build \
          --package node-template \
          --profile release \
          --features runtime-benchmarks

      - name: Run benchmarks
        run: |
          ./target/release/node-template benchmark pallet \
              --chain dev \
              --execution=wasm \
              --wasm-execution=compiled \
              --pallet pallet-template \
              --extrinsic "*" \
              --steps 50 \
              --repeat 20 \
              --json \
              > results.json

      - name: install jq
        run: sudo apt-get install jq 

      - name: Generate csv file
        run: cat results.json | jq -r '["extrinsic", "time (µs)"], (.[] | [ .benchmark, ([.time_results[]?.extrinsic_time] | (add / length) | round /1000 ) ]) | @csv' > results.csv

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install csv-to-markdown
        run: |
          sudo npm install --global csv-to-markdown

      - name: mkdir
        run: mkdir benchmark-results

      - name: Convert csv file to Markdown 
        run: |
          csv-to-markdown results.csv  \
          > benchmark-results/BENCHMARK.MD

      - name: Publish Benchmark results on GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./benchmark-results
          keep_files: true
          github_token: ${{ secrets.BENCH_RESULTS_ACCESS_TOKEN }}

     